### ISSUE TITLE
Browser history is not usable

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Kuran#13]
This request is from Prof Oğuz Borat:
> Ayetin mealine, sonra Mushaf'a bakarak ilerlerken bir kelimeye takılıyorum; yani muceme oradan geçtiği ayetlere girerek nasıl kullanıldığını anlamaya çalışıyorum; okuma yaptığım yerden epey uzaklaşmış, araya bir çok sayfalar girmiş oluyor. Tekrar kaldığım sayfaya dönmenin kolay yolu var mı? 

Browser history (alt-left arrow) is exactly for this purpose -- it doesn't work properly

Current implementation of history is not correct

**Comment by a0m0rajab** [comment]
The problem is that even if we have browser history, going backward is being an endless loop between the last two pages.
