### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Kuran#14]
Another request from Prof Oğuz Borat:
> [Kendi belirlediğim] konularda ayrı bir yere not yazma/toplama/derleme imkanı var mıdır? 

We need an [annotation system](https://en.wikipedia.org/wiki/Annotation) for Iqra

User should be able to add brief notes to each page/root/topic
Notes must be easily accessible and editable

**Comment by maeyler** [comment]
first step: add notes to Mushaf pages

define `class Notes `and add three lines:
```
const notes = new Notes('notesQ')
    notes.display(k)  //on open page k
    noteBut.onclick = () => {notes.edit()} 
```

**Comment by a0m0rajab** [comment]
Can we keep the notes in a drive file or even in the local storage to be able to use them in all applications (Iqra, Rehber) ?

**Comment by maeyler** [comment]
> Can we keep the notes in a drive file or even in the local storage to be able to use them in all applications (Iqra, Rehber) ?

* Current implementation uses `localStorage.notesQ` for Iqra
* Access to local drives is not allowed in Chrome (work is in progress)
* This code uses Google Drive (and 3rd party cookies)
https://okuyun.github.io/Kuran/bookmarks.html
but it doesn't work in all platforms (requires more work)
