### ISSUE TITLE
Nice-to-have

### ISSUE THREAD

**Issue by cpenbe** [Okuyun/Kuran#16]
1. To add a note on the home screen for mobile users which says they have the ability to install the page as an app on their screen (so they don't have to remember the link)
2. To use clearer and more descriptive icons for A and X buttons (e.g. Back, Home). Icons section at Google Fonts may be used for the same: https://fonts.google.com/icons

Thanx

**Comment by maeyler** [comment]
> 1. To add a note on the home screen for mobile users which says they have the ability to install the page as an app on their screen (so they don't have to remember the link)

We already have this feature in the menu: 
![image](https://user-images.githubusercontent.com/14038292/114450491-c11ed380-9bde-11eb-8523-7765d8736e06.png)
Do you want more than this?

> 2. To use clearer and more descriptive icons for A and X buttons (e.g. Back, Home). Icons section at Google Fonts may be used for the same: https://fonts.google.com/icons

Please make a suggestion for A icon
X is standard for closing a panel

**Comment by cpenbe** [comment]
One of the icons can be selected for "A" from below links:
https://fonts.google.com/icons?icon.query=home
https://www.iconfinder.com/search/?q=main+menu

**Comment by maeyler** [comment]
> 1. To add a note on the home screen for mobile users which says they have the ability to install the page as an app on their screen (so they don't have to remember the link)

I believe the current place for "Install..." in the menu is correct 

> 2. To use clearer and more descriptive icons for A and X buttons (e.g. Back, Home). 

x is standard for closing the panel
A is for "Access panel" or "Arama paneli"
Pink color indicates that these two buttons are somehow related (at a higher level than the text) and also we have another way to switch panels -- horizontal swipe now works in all panels

So my vote is to leave them as is

**Comment by maeyler** [comment]
World icon for language -- added recently
Home icon for start page -- added today
A and L icons are replaced
x remains as Close icon
