### ISSUE TITLE
Root option

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Kuran#18]
There was an option showing to show/hide the root of the word but it's missing now, or maybe I could not find it. 

The root of the words is working automatically if I used Mucem but could not access it without using it.

**Comment by a0m0rajab** [comment]
A screen recording for the issue. 

https://user-images.githubusercontent.com/18273833/118407263-ad0c3d00-b688-11eb-995d-eb1177b7ff9d.mp4

**Comment by maeyler** [comment]
The explanation is simple: MujamData (202KB) isn't loaded yet.
SimData (37KB) is much smaller, so it is loaded earlier.
When you go to another page MujamData is ready.

That's not an issue, normal delay at loading.
