### ISSUE TITLE
Root options conflict

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Kuran#19]
I faced this problem few days ago, but could not reproduce it now! I am writing it down for recording purpose. 

Mucem and Rehber is using the same root hash `#r` using rehber on the phone from Quran, looking for a root of the word, made the website to automatically open Mucem and leave rehber! the expected behaviour is to stay in rehber.

**Comment by maeyler** [comment]
It depends on the link:
* https://okuyun.github.io/Kuran/#r=tbb opens Mucem
* https://okuyun.github.io/Rehber/finder#r=tbb opens Rehber

It is convenient to have different tools for the same search -- I don't think this is an issue

**Comment by a0m0rajab** [comment]
You are right, for me it only happened once, you are right what I meant is to have two tools for the same search but for my case it was only opening Mucem.
