### ISSUE TITLE
Swipe bug 

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Kuran#20]
How to produce the problem: 
On Mobile Phone: 
- Searching for word from Quran (allah) for example
-  Trying to swipe fast to the end of the list (vertically) is causing the page to load again!

**Comment by maeyler** [comment]
Mobil cihazlarda sayfa çevirmek ve panel değiştirmek için bir haftadır kaydırma (swipe) kullanıyorum. Bazen istenmeyen hareketler yapıyor. Çözüm buluncaya kadar, ekranın altındaki "dönüş butonu" önceki yerinize geri getirecektir.

**Comment by maeyler** [comment]
Bu sorun büyük ölçüde çözüldü, küçük bir ayar problemi var -- bakıyorum
