### ISSUE TITLE
swipe enhancement 

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Kuran#21]
On quran and translation Swipe horizontally only works on the text itself its does not work on the blue area, could we enable it for the whole page?

**Comment by maeyler** [comment]
NO -- it's not worth the effort (except for `start.html`, the initial page)

Swipe is mainly for mobile devices where the screen is already full

**Comment by a0m0rajab** [comment]
For my mobile the Quran page is not full screen always.

**Comment by maeyler** [comment]
I tried making `start.html` full height -- it _did_ work

was simple -- thank you

**Comment by maeyler** [comment]
Now it works for `reader.html` -- Thanks to @a0m0rajab 

The reason why calc() did not work earlier:
> The + and - operators must be surrounded by whitespace.
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()
