### ISSUE TITLE
Swipes conflict - Pull to refresh

### ISSUE THREAD

**Issue by a0m0rajab** [Okuyun/Kuran#23]
The default chrome pull to refresh feature is intervening with the swipe down/up function we got and cause to fully refresh the page, which it's not a great UX. 

We can disable the default chrome feature to get the best UX for this app:  

https://w3bits.com/prevent-chrome-pull-to-refresh-css

**Comment by SmallSimpleSafe** [comment]
All problems related to swipe and resize seems to be solved

![image](https://user-images.githubusercontent.com/14292061/128807229-64cdc111-f3a9-4e4e-9bde-4907a478ebd3.png)
I found the cause for this problem:
resize listener and swipe listener used the same function!!
