### ISSUE TITLE
Issues with iPhone (Safari)

### ISSUE THREAD

**Issue by cpenbe** [Okuyun/Kuran#30]
1. Space, period and submit keys do not exist on the homepage keypad (contrary to Android), hence unable to write a surah/ayah pair, or directly go the intended page from there.

![no space and submit key](https://user-images.githubusercontent.com/27275064/151179572-3c2d5063-b9d7-43a6-bfdc-c0e538657615.jpeg)

2. This is the same when you click on the "Page" (Sayfa) option within the app.

![no period and submit key](https://user-images.githubusercontent.com/27275064/151179570-22edae81-d40c-4dff-9597-5c0041764760.jpeg)

3. No way to close the comment dialog after pressing the plus (+) sign.

![unable to close the dialog](https://user-images.githubusercontent.com/27275064/151179575-1d635833-2d06-4478-978e-d7bb9fc4056e.jpeg)

4. Menu and homepage icons do partly overlap.

![menu and homepage icons overlap](https://user-images.githubusercontent.com/27275064/151179563-671fe8d5-c51d-4171-a95e-126d62cfa7fb.jpeg)

Screenshots attached.

**Comment by maeyler** [comment]
HTML is a rich language -- we have solutions within HTML:

* Space, period and submit keys do not exist on the homepage keypad (contrary to Android),
The default stepping value for number inputs is 1, allowing only integers to be entered.
`step=any` should solve this issue

* No way to close the comment dialog after pressing the plus (+) sign.
You have two ways to hide the dialog: (this is not a bug)
<+> button on the window and &lt;Enter> key on the dialog​

* Menu and homepage icons do partly overlap.
`summary { list-style: none; }` hides the little triangle
![image](https://user-images.githubusercontent.com/14038292/151296645-e2f51805-c882-4097-9e44-f9435dfa1498.png) could be related to Chrome version
