### ISSUE TITLE
Not a bug just a short comment 🙂

### ISSUE THREAD

**Issue by takanome-dev** [Okuyun/Kuran#35]
Hey @maeyler @a0m0rajab, just wanted to say that this project is awesome 🤩 Love it 😍
This is probably the first project I saw about the `Quran` on Github and it just made my day.
Thanks so much for putting this together. Keep up the good work 💪. 🙏 جزاكم الله خيرا

**Comment by takanome-dev** [comment]
Okay, closing this now :sweat_smile:

**Comment by a0m0rajab** [comment]
Thank you for your message. It really made my day! And showed the importance of having such an open-source project. 😄 

Just to give some context: 

The idea of the project is for Prof. Akif, a Harvard graduate and university professor in Turkey. This was his vision for 40 years, and Alhamdulillah, I had the privilege to work with him. I could not work on such a project without him and his faith. And I learned a lot from him. Most importantly, virtues.  😄
