### ISSUE TITLE
Words missing in Mujam

### ISSUE THREAD

**Issue by SmallSimpleSafe** [Okuyun/Kuran#4]
barzah, tannur, nemâriq, zarâbiy

**Comment by maeyler** [comment]
Bu kelimeler Mucem'de çıkmıyor. 
[Kaynağından](https://corpus.quran.com/qurandictionary.jsp) baktım, orada da yoklar.
berzah -- 23:100, 25:53, 55:20
tennûr -- 11:40, 23:27
nemâriq -- 88:15
zerâbiy -- 88:16

**Comment by sozenmustafa** [comment]
berzah -- farsçadan arapçaya  Kur'an nüzül etmeden önce geçmiş bir kelime, isim.
tennûr -- isim
nemâriq -- 4 harfli isim (3'lü kök türevi değil)
zerâbiy -- isim, 3'lü kökten türeme-ancak anlam farkı oluşmuş sanki-

https://corpus.quran.com/qurandictionary.jsp (kaynak) 3'lü köklü fiillerden türeyen kelimeleri buluyorsa bu kelimeleri bulamayabilir. Ama bu durumda zerâbiy kelimesini bulması lazımdı. 

Mu'cem ul mufehreslerde - malumunuz- özel  isimler kısımları da var. 3'lü kökten türemeyen ve genellikle başka dillerden geçen kelimeler - ibrahim - gibi buralarda verilmiş. Belki yukardaki kelimeler bunlara dahil edilebilir. Gerçi Mahmut Çanga berzah kelimesini özel isimler kısmında göstermemiş. Kökten türeyen kelimeler kısmında göstermiş. (Kelimeleri araştırmada yardımcı olan H.Sözen'e teşekkürler)

**Comment by sozenmustafa** [comment]
zerâbiy kelimesinin araştırılmasında kullanılan kaynak(javascript te enterasan bir proje):

https://www.ejtaal.net/aa/#hw4=449,ll=1267,ls=5,la=1823,sg=473,ha=299,br=421,pr=70,aan=242,mgf=390,vi=178,kz=994,mr=287,mn=566,uqw=705,umr=458,ums=386,umj=331,ulq=859,uqa=173,uqq=137,bdw=h385,amr=h279,asb=h411,auh=h690,dhq=h231,mht=h374,msb=h103,tla=h55,amj=h318,ens=h1,mis=h1

**Comment by maeyler** [comment]
Bu kelimelerin kayda geçmesi yeter, şimdilik konuyu kapatıyorum
