### ISSUE TITLE
Visual cues for transliterated input

### ISSUE THREAD

**Issue by gulcu** [Okuyun/Kuran#5]
The user input text field labelled "Mucem'de bul" on the entry ([index.html](https://okuyun.github.io/Kuran/index.html)) page takes input in Latin letters and converts them to Arabic letters when the "Bul" button is pressed. Converting the transliteration into Arabic is done using the Buckwalter scheme. Since the scheme has arbitrary mappings which users may not know by heart, it would be useful to guide the input by textually hinting the current status of the conversion after each character edit, without waiting for the submission of the whole form. Additionally, either showing the Buckwalter table somewhere or at least providing a link to it would come in handy.

**Comment by maeyler** [comment]
> It would be useful to guide the input by textually hinting the current
> status of the conversion after each character edit, without waiting for the
> submission of the whole form.
>
This is quite difficult, since the modules communicate using Buckwalter
code (ASCII) not converted to Arabic (Unicode)

Users have the ability to find the desired root in the Arabic menus

> Additionally, either showing the Buckwalter table somewhere or at least
> providing a link to it would come in handy.
>
OK, this looks much simpler and doable

**Comment by maeyler** [comment]
Closed: [help for Buckwalter code](https://github.com/Okuyun/Kuran/commit/bbbde358ffca0971673f68edeb32889b3c3faa2f)

**Comment by sozenmustafa** [comment]
Solution is useful.
Thanks.
