### ISSUE TITLE
Continuous improvement

### ISSUE THREAD

**Issue by SmallSimpleSafe** [Okuyun/Kuran#7]
Minor issues and bugs that were resolved recently:
* add chap:verse to page number input
* Transparent pixels in [sura dividers](/Okuyun/Kuran/commit/94195b) (A Rajab)
* sura menu font size was fixed
* localStorage management
* save zoom state [in localStorage](/Okuyun/Kuran/commit/75b548)

**Comment by maeyler** [comment]
Font menu in Finder is active today
Reader uses the value selected:
`html.style.fontFamily = localStorage.settings.fontType`

Reader needs a shortcut to Finder settings dialog

**Comment by a0m0rajab** [comment]
since reader and finder is in the same origin we can use the same storage between them and watch the change on storage for both of them.

Ref:
Local storage same origin: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
Change Event: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

**Comment by a0m0rajab** [comment]
we can use the post message function as well: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

But I think the storage observation is enough.

**Comment by sozenmustafa** [comment]
2:72  فَٱدَّٰرَْٰٔتُمْ kelimesi yeni fontta da problemli sanırım.

**Comment by maeyler** [comment]
* Modify Iqra menu:
  Dış kaynaklar
  Dokümanlar => Yardım

* Help documents:
  Use "mdash;"
  Navigation fca8898

**Comment by maeyler** [comment]
* modify zoom icon (@Gulcu)

* responsive help menu (navigation)

* add video hints (@EbrarSena)

**Comment by maeyler** [comment]
**V4.1 is released**
* modified icons
* improved mujam
* resizable panels
* help pages & video
(Thanks to @EbrarSena)

**Comment by maeyler** [comment]
Thanks to @cpenbe
Celalettin gave us a new site -- new links are 12 char shorter
`replace("github.io/Kuran", "org")`

Examples:
https://okuyun.org/#r=rfE
https://okuyun.org/#v=27:30
https://okuyun.org/#m=index

**Comment by maeyler** [comment]
https://okuyun.github.io/
simplified

**Comment by gulcu** [comment]
I like this menu page because the layout is uncluttered, and the fonts are extremely readable. I wish the buttons exhibited hover effects like color transition, shadow etc. However, I'm not sure if the effort is justified if most targeted users presumably use their fingers instead of a mouse.

**Comment by maeyler** [comment]
> I wish the buttons exhibited hover effects like color transition, shadow etc. 

Color is implemented, shadow was not effective -- reverted

**Comment by maeyler** [comment]
Reason why shadow did not work:
I prefer &lt;a> tag that behave like a button (rather than &lt;button>)
because these are real links that look like buttons :)

**Comment by maeyler** [comment]
New improvements:
* "Ramazan notları" is completed
* Share API is used in context menus
* Touch event handling needs some testing 
(I expect #20 is fixed completely)

**Comment by maeyler** [comment]
Add star button to the start page

![image](https://user-images.githubusercontent.com/14038292/126732916-c62563dc-638a-432d-82ba-9e6cc8a875e1.png)

**Comment by maeyler** [comment]
V4.2 is out -- need to update the help page
* start page is improved
* swipe issue is solved
* works in incognito tab

**Comment by maeyler** [comment]
V4.2a -- two important features:
* Buttons (Star, Trans, Help) become menus if pressed 1/3 of a second
![context menu](https://user-images.githubusercontent.com/14038292/131504114-bf73d0b8-a4fa-4f0b-9129-133b7b124256.png)

* Trans menu has the ability to hide diacritical marks in Arabic text
![no vowels](https://user-images.githubusercontent.com/14038292/131504163-e197ff52-4d51-467f-bc03-814e45a7bcd9.png)
(This solves [the related issue](/Okuyun/Rehber/issues/13) in Rehber)

**Comment by maeyler** [comment]
V4.2b
* Button-menu concept is  abandoned -- entering a button displays menu
* Mujam: List mode is not transient -- the state is kept when selection is changed

**Comment by maeyler** [comment]
With the release of V4.2, the end of this phase is reached. New features will not be added until V5.0.

**Comment by SmallSimpleSafe** [comment]
Not a new feature, just improved structure:
* &lt;nav> for the top and bottom &lt;div> elements
* use flexbox to display navbars
* draw a little triangle on top of hover menus:
https://codeconvey.com/css-speech-bubble-with-border/

**Comment by maeyler** [comment]
This is V4.2c

**Comment by maeyler** [comment]
The image below shows the context menu and the hamburger menu:

<img width="341" alt="menu bubble" src="https://user-images.githubusercontent.com/14038292/134301708-6af155db-d194-4999-8da6-b3cf03e84b1e.png">

* Note the little triangle showing the button which is hovered or tapped
* Share menus are different: Verse or Page is shared
* External sources are also different
* <b>This is V4.2c</b>

**Comment by maeyler** [comment]
V4.3 is released today:
* German translation is added
* Menu behavior is standard: activated on hover
* Context-menu position on words is corrected
* Mujam links work correctly on multiple roots

**Comment by maeyler** [comment]
a0m0rajab commented on Feb 14:
> we can use the post message function as well: 
> https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

[implemented today](https://github.com/Okuyun/Kuran/commit/6ead13) -- with a delay of ten months
