### ISSUE TITLE
Spacing issue in a pull down menu

### ISSUE THREAD

**Issue by aymercan** [Okuyun/Kuran#9]
The spacing around "Dış Kaynaklar" seems a bit off. It would look much better if the space above that phrase would reflect the spacing convention around "IqraBeta1j".

<img width="130" alt="Screen Shot 2021-02-25 at 8 55 56 AM" src="https://user-images.githubusercontent.com/30095982/109110049-6d981980-7747-11eb-8ec3-4aa140fbebb4.png">

**Comment by a0m0rajab** [comment]
Dublicated issue: [issue](https://github.com/Okuyun/Kuran/issues/8). 
I will lock the conversation to focus on one of them.
